spring.application.name=linuxmate-server

server.port=8081
spring.datasource.username=postgres
spring.datasource.password=0801
spring.datasource.url=jdbc:postgresql://localhost:5432/linuxmate

# Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.security.user.name=admin
spring.security.user.password=admin
